name: opencvcdemo
base: core18
version: '0.1'
summary: Tool to convert a directory of images to a vector of normalized pixel values.
description: |
  This tool is used to convert a set of jpeg images to a vector of normalized pixel values. Usually used as a preprocessing step for machine learning/pattern recognition.

grade: devel
confinement: devmode

apps:
  opencvodemo:
    command: opencvcdemoprocess
    #daemon: simple #for automatic app start
    #extensions: [gnome-3-28]
    environment:
       "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas"


parts:
  #opencv-snap:
   # plugin: cmake
    #configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DWITH_CUDA=OFF]
    #build-packages:
     # - build-essential
     # - cmake
    #source: https://github.com/opencv/opencv/archive/4.5.3.tar.gz
    

  src-to-be-compiled:
    plugin: cmake
    source: ./
    build-packages:
      - build-essential
      - cmake
      - libopencv-dev
    stage-packages:
      - libopencv-dev
      - libopencv-contrib-dev
    #source: https://github.com/opencv/opencv/archive/4.5.3.tar.gz
    
    #after:
     # - opencv-snap
    
